services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: project-nest-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - MEILI_HOST=http://meilisearch:7700
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - mailpit
      - meilisearch

  redis:
    image: redis:7-alpine
    container_name: project-nest-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: project-nest-redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis

  mailpit:
    image: axllent/mailpit:latest
    container_name: project-nest-mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    environment:
      - MP_MAX_MESSAGES=5000
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: project-nest-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-devMasterKey123}
      - MEILI_ENV=development
    volumes:
      - meili-data:/meili_data

volumes:
  redis-data:
  redis-insight-data:
  meili-data:
